/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unimontes.ccet.dcc.pg1.view;

import br.unimontes.ccet.dcc.pg1.view.paineis.PainelCadastrarAluno;
import br.unimontes.ccet.dcc.pg1.view.paineis.AlunosSideMenu;
import br.unimontes.ccet.dcc.pg1.view.paineis.CursosSideMenu;
import br.unimontes.ccet.dcc.pg1.view.paineis.MatriculasSideMenu;
import java.awt.BorderLayout;
import java.awt.Color;
import static java.awt.Color.*;

/**
 *
 * @author m
 */
public class MainFrame extends javax.swing.JFrame {

    String currentMenu = "";

    public MainFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelBase1 = new br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase();
        PainelMatriculas = new javax.swing.JPanel();
        BtMatriculas = new javax.swing.JButton();
        PainelCursos = new javax.swing.JPanel();
        BtCursos = new javax.swing.JButton();
        PainelAlunos = new javax.swing.JPanel();
        BtAlunos = new javax.swing.JButton();

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton2.setText("Alunos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(790, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(790, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(790, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema RCB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        painelBase1.setBackground(new java.awt.Color(255, 255, 255));
        painelBase1.setMaximumSize(new java.awt.Dimension(800, 600));
        painelBase1.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout painelBase1Layout = new javax.swing.GroupLayout(painelBase1);
        painelBase1.setLayout(painelBase1Layout);
        painelBase1Layout.setHorizontalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelBase1Layout.setVerticalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        PainelMatriculas.setBackground(new java.awt.Color(0, 102, 153));
        PainelMatriculas.setMaximumSize(new java.awt.Dimension(790, 60));
        PainelMatriculas.setMinimumSize(new java.awt.Dimension(790, 60));

        BtMatriculas.setBackground(new java.awt.Color(0, 102, 153));
        BtMatriculas.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BtMatriculas.setForeground(new java.awt.Color(255, 255, 255));
        BtMatriculas.setText("Matrículas");
        BtMatriculas.setContentAreaFilled(false);
        BtMatriculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtMatriculasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtMatriculasMouseExited(evt);
            }
        });
        BtMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMatriculasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelMatriculasLayout = new javax.swing.GroupLayout(PainelMatriculas);
        PainelMatriculas.setLayout(PainelMatriculasLayout);
        PainelMatriculasLayout.setHorizontalGroup(
            PainelMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMatriculasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BtMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelMatriculasLayout.setVerticalGroup(
            PainelMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMatriculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelCursos.setBackground(new java.awt.Color(0, 102, 153));
        PainelCursos.setMaximumSize(new java.awt.Dimension(790, 60));
        PainelCursos.setMinimumSize(new java.awt.Dimension(790, 60));

        BtCursos.setBackground(new java.awt.Color(0, 102, 153));
        BtCursos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BtCursos.setForeground(new java.awt.Color(255, 255, 255));
        BtCursos.setText("Cursos");
        BtCursos.setContentAreaFilled(false);
        BtCursos.setPreferredSize(new java.awt.Dimension(193, 55));
        BtCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtCursosMouseExited(evt);
            }
        });
        BtCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCursosLayout = new javax.swing.GroupLayout(PainelCursos);
        PainelCursos.setLayout(PainelCursosLayout);
        PainelCursosLayout.setHorizontalGroup(
            PainelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCursosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(BtCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelCursosLayout.setVerticalGroup(
            PainelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelAlunos.setBackground(new java.awt.Color(0, 102, 153));
        PainelAlunos.setMaximumSize(new java.awt.Dimension(790, 60));
        PainelAlunos.setMinimumSize(new java.awt.Dimension(790, 60));

        BtAlunos.setBackground(new java.awt.Color(0, 102, 153));
        BtAlunos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BtAlunos.setForeground(new java.awt.Color(255, 255, 255));
        BtAlunos.setText("Alunos");
        BtAlunos.setBorderPainted(false);
        BtAlunos.setContentAreaFilled(false);
        BtAlunos.setFocusPainted(false);
        BtAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtAlunosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtAlunosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtAlunosMouseExited(evt);
            }
        });
        BtAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlunosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelAlunosLayout = new javax.swing.GroupLayout(PainelAlunos);
        PainelAlunos.setLayout(PainelAlunosLayout);
        PainelAlunosLayout.setHorizontalGroup(
            PainelAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAlunosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BtAlunos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelAlunosLayout.setVerticalGroup(
            PainelAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAlunosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PainelAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(PainelMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(painelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(PainelAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelMatriculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(painelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlunosActionPerformed
        currentMenu = "Alunos";
        PainelCursos.setBackground(new Color(0, 102, 153));
        PainelMatriculas.setBackground(new Color(0, 102, 153));
        PainelAlunos.setBackground(new Color(0, 51, 102));

        AlunosSideMenu smenu = new AlunosSideMenu();
        smenu.setSize(800, 600);
        smenu.setLocation(0, 0);
        painelBase1.removeAll();
        painelBase1.repaint();
        painelBase1.revalidate();
        painelBase1.add(smenu, BorderLayout.CENTER);
        painelBase1.repaint();
        painelBase1.revalidate();

    }//GEN-LAST:event_BtAlunosActionPerformed

    private void BtCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCursosActionPerformed
        currentMenu = "Cursos";
        PainelAlunos.setBackground(new Color(0, 102, 153));
        PainelMatriculas.setBackground(new Color(0, 102, 153));
        PainelCursos.setBackground(new Color(0, 51, 102));
        CursosSideMenu smenu = new CursosSideMenu();
        smenu.setSize(800, 600);
        smenu.setLocation(0, 0);
        painelBase1.removeAll();
        painelBase1.repaint();
        painelBase1.revalidate();
        painelBase1.add(smenu, BorderLayout.CENTER);
        painelBase1.repaint();
        painelBase1.revalidate();
    }//GEN-LAST:event_BtCursosActionPerformed

    private void BtMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMatriculasActionPerformed
        currentMenu = "Matriculas";
        PainelAlunos.setBackground(new Color(0, 102, 153));
        PainelCursos.setBackground(new Color(0, 102, 153));
        PainelMatriculas.setBackground(new Color(0, 51, 102));
        MatriculasSideMenu smenu = new MatriculasSideMenu();
        smenu.setSize(800, 600);
        smenu.setLocation(0, 0);
        painelBase1.removeAll();
        painelBase1.repaint();
        painelBase1.revalidate();
        painelBase1.add(smenu, BorderLayout.CENTER);
        painelBase1.repaint();
        painelBase1.revalidate();
    }//GEN-LAST:event_BtMatriculasActionPerformed

    private void BtAlunosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtAlunosMouseEntered
        PainelAlunos.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_BtAlunosMouseEntered
    private void BtAlunosMouseExited(java.awt.event.MouseEvent evt) {
        if (currentMenu != "Alunos") {
            PainelAlunos.setBackground(new Color(0, 102, 153));
        }

    }
    private void BtAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtAlunosMouseClicked

    }//GEN-LAST:event_BtAlunosMouseClicked

    private void BtMatriculasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtMatriculasMouseEntered
        PainelMatriculas.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_BtMatriculasMouseEntered
    /**//*
    private void BtAlunosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtAlunosMouseExited
        jPanel8.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_BtAlunosMouseExited
*/
    private void BtCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtCursosMouseEntered
        PainelCursos.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_BtCursosMouseEntered

    private void BtCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtCursosMouseExited
        if(currentMenu != "Cursos")PainelCursos.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_BtCursosMouseExited

    private void BtMatriculasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtMatriculasMouseExited
        if(currentMenu != "Matriculas")PainelMatriculas.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_BtMatriculasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlunos;
    private javax.swing.JButton BtCursos;
    private javax.swing.JButton BtMatriculas;
    private javax.swing.JPanel PainelAlunos;
    private javax.swing.JPanel PainelCursos;
    private javax.swing.JPanel PainelMatriculas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase painelBase1;
    // End of variables declaration//GEN-END:variables
}
