/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unimontes.ccet.dcc.pg1.view.paineis;

import java.awt.Color;

/**
 *
 * @author m
 */
public class AlunosSideMenu extends javax.swing.JPanel {
    String currentSubMenu ="";
    /**
     * Creates new form AlunosSideMenu
     */
    public AlunosSideMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CadastrarPanel = new javax.swing.JPanel();
        CadastrarButton = new javax.swing.JButton();
        ConsultarPanel = new javax.swing.JPanel();
        ConsultarButton = new javax.swing.JButton();
        painelBase1 = new br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        CadastrarPanel.setBackground(new java.awt.Color(0, 51, 102));

        CadastrarButton.setBackground(new java.awt.Color(255, 255, 255));
        CadastrarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CadastrarButton.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarButton.setText("Cadastrar");
        CadastrarButton.setContentAreaFilled(false);
        CadastrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadastrarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadastrarButtonMouseExited(evt);
            }
        });
        CadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastrarPanelLayout = new javax.swing.GroupLayout(CadastrarPanel);
        CadastrarPanel.setLayout(CadastrarPanelLayout);
        CadastrarPanelLayout.setHorizontalGroup(
            CadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        CadastrarPanelLayout.setVerticalGroup(
            CadastrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastrarPanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(CadastrarButton)
                .addGap(8, 8, 8))
        );

        ConsultarPanel.setBackground(new java.awt.Color(0, 51, 102));

        ConsultarButton.setBackground(new java.awt.Color(255, 255, 255));
        ConsultarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ConsultarButton.setForeground(new java.awt.Color(255, 255, 255));
        ConsultarButton.setText("Consultar");
        ConsultarButton.setContentAreaFilled(false);
        ConsultarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConsultarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConsultarButtonMouseExited(evt);
            }
        });
        ConsultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultarPanelLayout = new javax.swing.GroupLayout(ConsultarPanel);
        ConsultarPanel.setLayout(ConsultarPanelLayout);
        ConsultarPanelLayout.setHorizontalGroup(
            ConsultarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConsultarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConsultarPanelLayout.setVerticalGroup(
            ConsultarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(ConsultarButton)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastrarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ConsultarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CadastrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ConsultarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painelBase1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout painelBase1Layout = new javax.swing.GroupLayout(painelBase1);
        painelBase1.setLayout(painelBase1Layout);
        painelBase1Layout.setHorizontalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        painelBase1Layout.setVerticalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
        currentSubMenu = "Cadastrar";
        ConsultarPanel.setBackground(new Color(0,51,102));
        painelBase1.removeAll();
        painelBase1.repaint();
        painelBase1.revalidate();
        PainelCadastrarAluno pAluno = new PainelCadastrarAluno();
        pAluno.setSize(painelBase1.getWidth(),painelBase1.getHeight());
        painelBase1.add(pAluno);
        painelBase1.repaint();
        painelBase1.revalidate();
        
    }//GEN-LAST:event_CadastrarButtonActionPerformed

    private void ConsultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarButtonActionPerformed
        currentSubMenu = "Consultar";
        CadastrarPanel.setBackground(new Color(0,51,102));
        painelBase1.removeAll();
        painelBase1.repaint();
        painelBase1.revalidate();
        PainelConsultaAluno pAluno = new PainelConsultaAluno();
        pAluno.setSize(painelBase1.getWidth(),painelBase1.getHeight());
        painelBase1.add(pAluno);
        painelBase1.repaint();
        painelBase1.revalidate();
    }//GEN-LAST:event_ConsultarButtonActionPerformed

    private void CadastrarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarButtonMouseEntered
        CadastrarPanel.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_CadastrarButtonMouseEntered

    private void ConsultarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarButtonMouseEntered
        ConsultarPanel.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_ConsultarButtonMouseEntered

    private void CadastrarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarButtonMouseExited
        if(currentSubMenu != "Cadastrar")CadastrarPanel.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_CadastrarButtonMouseExited

    private void ConsultarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarButtonMouseExited
        if(currentSubMenu != "Consultar")ConsultarPanel.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_ConsultarButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JPanel CadastrarPanel;
    private javax.swing.JButton ConsultarButton;
    private javax.swing.JPanel ConsultarPanel;
    private javax.swing.JPanel jPanel1;
    private br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase painelBase1;
    // End of variables declaration//GEN-END:variables
}
