/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unimontes.ccet.dcc.pg1.view.paineis;

import java.awt.Color;

/**
 *
 * @author m
 */
public class CursosSideMenu extends javax.swing.JPanel {

    String currentSubMenu = "";

    /**
     * Creates new form AlunosSideMenu
     */
    public CursosSideMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CadastrarPanel1 = new javax.swing.JPanel();
        CadastrarButton1 = new javax.swing.JButton();
        ConsultarPanel1 = new javax.swing.JPanel();
        ConsultarButton1 = new javax.swing.JButton();
        painelBase1 = new br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        CadastrarPanel1.setBackground(new java.awt.Color(0, 51, 102));

        CadastrarButton1.setBackground(new java.awt.Color(0, 51, 102));
        CadastrarButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CadastrarButton1.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarButton1.setText("Cadastrar");
        CadastrarButton1.setContentAreaFilled(false);
        CadastrarButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadastrarButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadastrarButton1MouseExited(evt);
            }
        });
        CadastrarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastrarPanel1Layout = new javax.swing.GroupLayout(CadastrarPanel1);
        CadastrarPanel1.setLayout(CadastrarPanel1Layout);
        CadastrarPanel1Layout.setHorizontalGroup(
            CadastrarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CadastrarButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        CadastrarPanel1Layout.setVerticalGroup(
            CadastrarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(CadastrarButton1)
                .addGap(8, 8, 8))
        );

        ConsultarPanel1.setBackground(new java.awt.Color(0, 51, 102));

        ConsultarButton1.setBackground(new java.awt.Color(0, 51, 102));
        ConsultarButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ConsultarButton1.setForeground(new java.awt.Color(255, 255, 255));
        ConsultarButton1.setText("Consultar");
        ConsultarButton1.setContentAreaFilled(false);
        ConsultarButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConsultarButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConsultarButton1MouseExited(evt);
            }
        });
        ConsultarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultarPanel1Layout = new javax.swing.GroupLayout(ConsultarPanel1);
        ConsultarPanel1.setLayout(ConsultarPanel1Layout);
        ConsultarPanel1Layout.setHorizontalGroup(
            ConsultarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConsultarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        ConsultarPanel1Layout.setVerticalGroup(
            ConsultarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultarPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(ConsultarButton1)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastrarPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ConsultarPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CadastrarPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ConsultarPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelBase1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout painelBase1Layout = new javax.swing.GroupLayout(painelBase1);
        painelBase1.setLayout(painelBase1Layout);
        painelBase1Layout.setHorizontalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        painelBase1Layout.setVerticalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButton1ActionPerformed
        currentSubMenu = "Cadastrar";
        ConsultarPanel1.setBackground(new Color(0, 51, 102));
        painelBase1.removeAll();
        painelBase1.repaint();
        painelBase1.revalidate();
        PainelCadastrarCurso pCurso = new PainelCadastrarCurso();
        pCurso.setSize(painelBase1.getWidth(), painelBase1.getHeight());
        painelBase1.add(pCurso);
        painelBase1.repaint();
        painelBase1.revalidate();

    }//GEN-LAST:event_CadastrarButton1ActionPerformed

    private void ConsultarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarButton1ActionPerformed
        currentSubMenu = "Consultar";
        CadastrarPanel1.setBackground(new Color(0,51,102));
        painelBase1.removeAll();
        painelBase1.repaint();
        painelBase1.revalidate();
        PainelConsultaCurso pCurso = new PainelConsultaCurso();
        pCurso.setSize(painelBase1.getWidth(), painelBase1.getHeight());
        painelBase1.add(pCurso);
        painelBase1.repaint();
        painelBase1.revalidate();
    }//GEN-LAST:event_ConsultarButton1ActionPerformed

    private void CadastrarButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarButton1MouseEntered
        CadastrarPanel1.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_CadastrarButton1MouseEntered

    private void CadastrarButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarButton1MouseExited
       if(currentSubMenu != "Consultar")ConsultarPanel1.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_CadastrarButton1MouseExited

    private void ConsultarButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarButton1MouseEntered
        ConsultarPanel1.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_ConsultarButton1MouseEntered

    private void ConsultarButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarButton1MouseExited
       if(currentSubMenu != "Consultar")ConsultarPanel1.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_ConsultarButton1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarButton1;
    private javax.swing.JPanel CadastrarPanel1;
    private javax.swing.JButton ConsultarButton1;
    private javax.swing.JPanel ConsultarPanel1;
    private javax.swing.JPanel jPanel1;
    private br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase painelBase1;
    // End of variables declaration//GEN-END:variables
}
