/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unimontes.ccet.dcc.pg1.view.paineis;

import java.awt.Color;

/**
 *
 * @author m
 */
public class MatriculasSideMenu extends javax.swing.JPanel {

    String currentSubMenu = "";

    /**
     * Creates new form AlunosSideMenu
     */
    public MatriculasSideMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MatricularPanel = new javax.swing.JPanel();
        MatricularButton = new javax.swing.JButton();
        ConsultarPanel = new javax.swing.JPanel();
        ConsultarButton = new javax.swing.JButton();
        painelBase1 = new br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        MatricularPanel.setBackground(new java.awt.Color(0, 51, 102));

        MatricularButton.setBackground(new java.awt.Color(255, 255, 255));
        MatricularButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MatricularButton.setForeground(new java.awt.Color(255, 255, 255));
        MatricularButton.setText("Matricular");
        MatricularButton.setBorderPainted(false);
        MatricularButton.setContentAreaFilled(false);
        MatricularButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MatricularButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MatricularButtonMouseExited(evt);
            }
        });
        MatricularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatricularButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MatricularPanelLayout = new javax.swing.GroupLayout(MatricularPanel);
        MatricularPanel.setLayout(MatricularPanelLayout);
        MatricularPanelLayout.setHorizontalGroup(
            MatricularPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatricularPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MatricularButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        MatricularPanelLayout.setVerticalGroup(
            MatricularPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatricularPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(MatricularButton)
                .addGap(8, 8, 8))
        );

        ConsultarPanel.setBackground(new java.awt.Color(0, 51, 102));

        ConsultarButton.setBackground(new java.awt.Color(0, 51, 102));
        ConsultarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ConsultarButton.setForeground(new java.awt.Color(255, 255, 255));
        ConsultarButton.setText("Consultar");
        ConsultarButton.setBorderPainted(false);
        ConsultarButton.setContentAreaFilled(false);
        ConsultarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConsultarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConsultarButtonMouseExited(evt);
            }
        });
        ConsultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultarPanelLayout = new javax.swing.GroupLayout(ConsultarPanel);
        ConsultarPanel.setLayout(ConsultarPanelLayout);
        ConsultarPanelLayout.setHorizontalGroup(
            ConsultarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConsultarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConsultarPanelLayout.setVerticalGroup(
            ConsultarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(ConsultarButton)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MatricularPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ConsultarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(MatricularPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ConsultarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelBase1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout painelBase1Layout = new javax.swing.GroupLayout(painelBase1);
        painelBase1.setLayout(painelBase1Layout);
        painelBase1Layout.setHorizontalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        painelBase1Layout.setVerticalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MatricularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatricularButtonActionPerformed
        currentSubMenu = "Matricular";
        ConsultarPanel.setBackground(new Color(0, 51, 102));
        painelBase1.removeAll();
        painelBase1.repaint();
        painelBase1.revalidate();
        PainelCadastrarMatricula pMat = new PainelCadastrarMatricula();
        pMat.setSize(painelBase1.getWidth(), painelBase1.getHeight());
        painelBase1.add(pMat);
        painelBase1.repaint();
        painelBase1.revalidate();

    }//GEN-LAST:event_MatricularButtonActionPerformed

    private void ConsultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarButtonActionPerformed
        currentSubMenu = "Consultar";
        MatricularPanel.setBackground(new Color(0, 51, 102));
        painelBase1.removeAll();
        painelBase1.repaint();
        painelBase1.revalidate();
        PainelConsultaMatricula pMat = new PainelConsultaMatricula();
        pMat.setSize(painelBase1.getWidth(), painelBase1.getHeight());
        painelBase1.add(pMat);
        painelBase1.repaint();
        painelBase1.revalidate();
    }//GEN-LAST:event_ConsultarButtonActionPerformed

    private void MatricularButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatricularButtonMouseEntered
        MatricularPanel.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_MatricularButtonMouseEntered

    private void MatricularButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatricularButtonMouseExited
        MatricularPanel.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_MatricularButtonMouseExited

    private void ConsultarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarButtonMouseEntered
        ConsultarPanel.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_ConsultarButtonMouseEntered

    private void ConsultarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarButtonMouseExited
         if(currentSubMenu != "Consultar")ConsultarPanel.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_ConsultarButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarButton;
    private javax.swing.JPanel ConsultarPanel;
    private javax.swing.JButton MatricularButton;
    private javax.swing.JPanel MatricularPanel;
    private javax.swing.JPanel jPanel1;
    private br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase painelBase1;
    // End of variables declaration//GEN-END:variables
}
