/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unimontes.ccet.dcc.pg1.view.paineis;

import br.unimontes.ccet.dcc.pg1.controller.DeletarAlunoCursoController;
import br.unimontes.ccet.dcc.pg1.model.dao.AlunoDao;
import br.unimontes.ccet.dcc.pg1.model.dao.exception.DAOException;
import br.unimontes.ccet.dcc.pg1.model.entity.Aluno;
import br.unimontes.ccet.dcc.pg1.view.interfaces.PainelInterface;
import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import br.unimontes.ccet.dcc.pg1.controller.ConsultarAlunoController;
import br.unimontes.ccet.dcc.pg1.controller.DeletarAlunoController;
import br.unimontes.ccet.dcc.pg1.controller.DeletarAlunoControllerTabela;
import br.unimontes.ccet.dcc.pg1.view.componentes.TableActionCellEditor;
import br.unimontes.ccet.dcc.pg1.view.componentes.TableActionCellRender;
import br.unimontes.ccet.dcc.pg1.view.interfaces.TableActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author m
 */
public class PainelConsultaAluno extends javax.swing.JPanel {

    /**
     * Creates new form PainelConsultaAluno
     */
    public PainelConsultaAluno() {
        initComponents();
        PreencherTabela();
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                painelBase1.removeAll();
                painelBase1.repaint();
                painelBase1.revalidate();
                Aluno a = new Aluno();
                a.setCpf((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                a.setNome((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                a.setAnoNascimento((Integer) jTable1.getValueAt(jTable1.getSelectedRow(), 2));
                PainelUpdateAluno pAluno = new PainelUpdateAluno(a);
                pAluno.setSize(painelBase1.getWidth(), painelBase1.getHeight());
                painelBase1.add(pAluno);
                painelBase1.repaint();
                painelBase1.revalidate();
            }

            @Override
            public void onDelete(int row) {
                int confirm = JOptionPane.showConfirmDialog(painelBase1, "Deseja relamente deletar o aluno?",
                        "Deletar Aluno", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (confirm == JOptionPane.YES_OPTION) {
                    try {
                        boolean ret = DeletarAlunoControllerTabela.executaTabela(lableAux.getText());
                        DeletarAlunoCursoController.deleteFromCpf(lableAux.getText());
                        PreencherTabela();
                        //DeletarAlunoController.executa(painelBase1);
                        if (ret) {
                            JOptionPane.showMessageDialog(painelBase1, "Aluno deletado com sucesso!");
                        } else {
                            JOptionPane.showMessageDialog(painelBase1, "Aluno não deletado!");
                        }
                    } catch (DAOException ex) {
                        Logger.getLogger(PainelConsultaAluno.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };

        jTable1.getColumnModel().getColumn(3).setCellRenderer(new TableActionCellRender());
        jTable1.getColumnModel().getColumn(3).setCellEditor(new TableActionCellEditor(event));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBase1 = new br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lableAux = new javax.swing.JLabel();
        tfNome = new br.unimontes.ccet.dcc.pg1.view.componentes.TextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(780, 590));
        setMinimumSize(new java.awt.Dimension(780, 590));
        setPreferredSize(new java.awt.Dimension(780, 590));

        painelBase1.setBackground(new java.awt.Color(255, 255, 255));
        painelBase1.setMaximumSize(new java.awt.Dimension(780, 590));
        painelBase1.setMinimumSize(new java.awt.Dimension(780, 590));
        painelBase1.setPreferredSize(new java.awt.Dimension(780, 590));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Data de Nascimento", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Consultar Alunos");

        lableAux.setBackground(new java.awt.Color(255, 255, 255));
        lableAux.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        lableAux.setForeground(new java.awt.Color(255, 255, 255));

        tfNome.setName("tfNome"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome do Aluno:");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Matricular Aluno");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBase1Layout = new javax.swing.GroupLayout(painelBase1);
        painelBase1.setLayout(painelBase1Layout);
        painelBase1Layout.setHorizontalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBase1Layout.createSequentialGroup()
                .addGroup(painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBase1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelBase1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lableAux, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelBase1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelBase1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBase1Layout.setVerticalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBase1Layout.createSequentialGroup()
                .addGroup(painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBase1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lableAux, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBase1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)))
                .addGroup(painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBase1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
private void PreencherTabela() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        ArrayList<Aluno> alunos = ConsultarAlunoController.addRowToJTable(painelBase1);
        alunos.forEach((Aluno aluno) -> {
            model.addRow(new Object[]{aluno.getCpf(), aluno.getNome(), aluno.getAnoNascimento()});
        });
        jTable1.setModel(model);

    }

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        DefaultTableModel d1 = (DefaultTableModel) jTable1.getModel();
        lableAux.setText("" + d1.getValueAt(jTable1.getSelectedRow(), 0));

    }//GEN-LAST:event_jTable1FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String aConsulta = tfNome.getText();
        if (aConsulta == null) {
            PreencherTabela();
            return;
        }
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
        ConsultarAlunoController a = new ConsultarAlunoController();

        ArrayList<Aluno> alunos = ConsultarAlunoController.consulta(aConsulta);
        ;
        alunos.forEach((Aluno aluno) -> {
            model.addRow(new Object[]{aluno.getCpf(), aluno.getNome(), aluno.getAnoNascimento()});
        });
        jTable1.setModel(tableModel);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        painelBase1.removeAll();
        painelBase1.repaint();
        painelBase1.revalidate();
        Aluno a = new Aluno();
        String nome = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 1);
        tfNome.setText(nome);
        a.setNome(nome);
        a.setCpf(ConsultarAlunoController.findCpf(nome));
        PainelCadastrarMatricula pMat = new PainelCadastrarMatricula(a);
        pMat.setSize(painelBase1.getWidth(), painelBase1.getHeight());
        painelBase1.add(pMat);
        painelBase1.repaint();
        painelBase1.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lableAux;
    private br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase painelBase1;
    private br.unimontes.ccet.dcc.pg1.view.componentes.TextField tfNome;
    // End of variables declaration//GEN-END:variables
}
