/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unimontes.ccet.dcc.pg1.view.paineis;

import br.unimontes.ccet.dcc.pg1.model.dao.AlunoDao;
import br.unimontes.ccet.dcc.pg1.model.dao.exception.DAOException;
import br.unimontes.ccet.dcc.pg1.model.entity.Aluno;
import br.unimontes.ccet.dcc.pg1.view.interfaces.PainelInterface;
import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import br.unimontes.ccet.dcc.pg1.controller.ConsultarAlunoController;
import br.unimontes.ccet.dcc.pg1.controller.ConsultarAlunoCursoController;
import br.unimontes.ccet.dcc.pg1.controller.ConsultarCursoController;
import br.unimontes.ccet.dcc.pg1.controller.DeletarAlunoControllerTabela;
import br.unimontes.ccet.dcc.pg1.controller.DeletarAlunoCursoControllerTabela;
import br.unimontes.ccet.dcc.pg1.model.entity.AlunoCurso;
import br.unimontes.ccet.dcc.pg1.model.entity.Curso;
import br.unimontes.ccet.dcc.pg1.view.componentes.TableActionCellEditor;
import br.unimontes.ccet.dcc.pg1.view.componentes.TableActionCellRender;
import br.unimontes.ccet.dcc.pg1.view.interfaces.TableActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author m
 */
public class PainelConsultaMatricula extends javax.swing.JPanel {

    /**
     * Creates new form PainelConsultaAluno
     */
    public PainelConsultaMatricula() {
        initComponents();
        PreencherTabela();
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                painelBase1.removeAll();
                painelBase1.repaint();
                painelBase1.revalidate();
                AlunoCurso a = new AlunoCurso();
                a.setCpf((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                a.setIdCurso((Integer) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                a.setCreditos((Integer) jTable1.getValueAt(jTable1.getSelectedRow(), 2));
                PainelUpdateMatricula pMat = new PainelUpdateMatricula(a);
                pMat.setSize(painelBase1.getWidth(), painelBase1.getHeight());
                painelBase1.add(pMat);
                painelBase1.repaint();
                painelBase1.revalidate();
            }

            @Override
            public void onDelete(int row) {
                int confirm = JOptionPane.showConfirmDialog(painelBase1, "Deseja relamente desmatricular o aluno?",
                        "Desmatricular Aluno", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (confirm == JOptionPane.YES_OPTION) {
                    boolean ret = DeletarAlunoCursoControllerTabela.executaTabela(lableAux.getText(),
                            Integer.parseInt(lableAuxCurso.getText()));
                    PreencherTabela();
                    //DeletarAlunoController.executa(painelBase1);
                    if (ret) {
                        JOptionPane.showMessageDialog(painelBase1, "Aluno desmatriculado com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(painelBase1, "Aluno não deletado!");
                    }
                }
            }
        };

        jTable1.getColumnModel().getColumn(3).setCellRenderer(new TableActionCellRender());
        jTable1.getColumnModel().getColumn(3).setCellEditor(new TableActionCellEditor(event));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBase1 = new br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tfNomeCurso = new br.unimontes.ccet.dcc.pg1.view.componentes.TextField();
        jLabel3 = new javax.swing.JLabel();
        tfNome = new br.unimontes.ccet.dcc.pg1.view.componentes.TextField();
        CursoConsultaButton = new javax.swing.JButton();
        AlunoConsultaButton = new javax.swing.JButton();
        lableAux = new javax.swing.JLabel();
        lableAuxCurso = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        painelBase1.setBackground(new java.awt.Color(255, 255, 255));
        painelBase1.setMaximumSize(new java.awt.Dimension(600, 550));
        painelBase1.setMinimumSize(new java.awt.Dimension(600, 550));
        painelBase1.setPreferredSize(new java.awt.Dimension(600, 550));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Consultar Matrículas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cpf do Aluno", "Id do curso", "Creditos", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome do Curso:");

        tfNomeCurso.setName("tfNomeCurso"); // NOI18N
        tfNomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeCursoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome do Aluno:");

        tfNome.setName("tfNome"); // NOI18N

        CursoConsultaButton.setText("Consultar");
        CursoConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursoConsultaButtonActionPerformed(evt);
            }
        });

        AlunoConsultaButton.setText("Consultar");
        AlunoConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlunoConsultaButtonActionPerformed(evt);
            }
        });

        lableAux.setBackground(new java.awt.Color(255, 255, 255));
        lableAux.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        lableAux.setForeground(new java.awt.Color(255, 255, 255));

        lableAuxCurso.setBackground(new java.awt.Color(255, 255, 255));
        lableAuxCurso.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        lableAuxCurso.setForeground(new java.awt.Color(255, 255, 255));
        lableAuxCurso.setName("lableAuxCurso"); // NOI18N

        javax.swing.GroupLayout painelBase1Layout = new javax.swing.GroupLayout(painelBase1);
        painelBase1.setLayout(painelBase1Layout);
        painelBase1Layout.setHorizontalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBase1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(138, 138, 138))
            .addGroup(painelBase1Layout.createSequentialGroup()
                .addGroup(painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBase1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelBase1Layout.createSequentialGroup()
                                .addGroup(painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AlunoConsultaButton)
                                    .addComponent(CursoConsultaButton)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelBase1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lableAux, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lableAuxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        painelBase1Layout.setVerticalGroup(
            painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBase1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlunoConsultaButton))
                .addGap(26, 26, 26)
                .addGroup(painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CursoConsultaButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(painelBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableAux, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableAuxCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AlunoConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlunoConsultaButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String aConsulta = tfNome.getText();
        if (aConsulta == null) {
            PreencherTabela();
            return;
        }
        String cpf = ConsultarAlunoController.findCpf(painelBase1);
        System.out.println(cpf);
        if (aConsulta == null) {
            PreencherTabela();
            return;
        }
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
        ConsultarAlunoCursoController a = new ConsultarAlunoCursoController();

        ArrayList<AlunoCurso> aCursos = ConsultarAlunoCursoController.consulta(cpf);
        ;
        aCursos.forEach((AlunoCurso acurso) -> {
            model.addRow(new Object[]{acurso.getCpf(), acurso.getIdCurso(), acurso.getCreditos()});
        });
        jTable1.setModel(tableModel);
    }//GEN-LAST:event_AlunoConsultaButtonActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        DefaultTableModel d1 = (DefaultTableModel) jTable1.getModel();
        lableAux.setText("" + d1.getValueAt(jTable1.getSelectedRow(), 0));
        lableAuxCurso.setText("" + d1.getValueAt(jTable1.getSelectedRow(), 1));
    }//GEN-LAST:event_jTable1FocusGained

    private void CursoConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursoConsultaButtonActionPerformed
        PreencherTabela();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String aConsulta = tfNomeCurso.getText();
        if (aConsulta == null) {
            PreencherTabela();
            return;
        }
        Integer id = ConsultarCursoController.findId(painelBase1);
        //System.out.println(id);
        if (aConsulta == null) {
            PreencherTabela();
            return;
        }
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
        ConsultarAlunoCursoController a = new ConsultarAlunoCursoController();

        ArrayList<AlunoCurso> aCursos = ConsultarAlunoCursoController.consulta(id);
        ;
        aCursos.forEach((AlunoCurso acurso) -> {
            model.addRow(new Object[]{acurso.getCpf(), acurso.getIdCurso(), acurso.getCreditos()});
        });
        jTable1.setModel(tableModel);
    }//GEN-LAST:event_CursoConsultaButtonActionPerformed

    private void tfNomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeCursoActionPerformed
    private void PreencherTabela() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        ArrayList<AlunoCurso> aCursos = ConsultarAlunoCursoController.addRowToJTable(painelBase1);
        aCursos.forEach((AlunoCurso aCurso) -> {
            model.addRow(new Object[]{aCurso.getCpf(), aCurso.getIdCurso(), aCurso.getCreditos()});
        });
        jTable1.setModel(model);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlunoConsultaButton;
    private javax.swing.JButton CursoConsultaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lableAux;
    private javax.swing.JLabel lableAuxCurso;
    private br.unimontes.ccet.dcc.pg1.view.paineis.PainelBase painelBase1;
    private br.unimontes.ccet.dcc.pg1.view.componentes.TextField tfNome;
    private br.unimontes.ccet.dcc.pg1.view.componentes.TextField tfNomeCurso;
    // End of variables declaration//GEN-END:variables
}
